---
apiVersion: litmuschaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  name: vmware
  version: 0.1.0
  annotations:
    categories: VMware
    chartDescription: Injects faults on VMware system
    executionPlane: "kubernetes"
spec:
  displayName: VMware
  categoryDescription: >
    VMware chaos contains different experiments for VMware platform. It uses VMware apis to carry out the fault logic for different components.
  faults:
    - name: vm-poweroff
      description: It injects power-off chaos on VMware VMs.
      displayName: "VMware VM Poweroff"
      svgImage: data:image/svg+xml;base64,PHN2ZyBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCA2NzggMTAzLjQiIHZpZXdCb3g9IjAgMCA2NzggMTAzLjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0iIzcxNzA3MyI+PHBhdGggZD0ibTI5MS4zIDk1LjYtMjkuNy04Mi43Yy0uNC0xLjEtLjktMi43LS45LTQgMC0zLjYgMy03IDcuNC03IDMuOCAwIDYuMyAyLjUgNy40IDZsMjQuNiA3MS4yIDI0LjgtNzEuNGMxLjEtMy40IDMuNC01LjggNy4yLTUuOGguOGM0IDAgNi40IDIuNSA3LjYgNS44bDI0LjYgNzEuMyAyNS03MS42YzEtMyAzLTUuNyA3LTUuNyA0LjIgMCA3LjIgMy4yIDcuMiA2LjggMCAxLjMtLjYgMi44LS45IDRsLTI5LjkgODIuOGMtMS41IDQuMy00LjUgNi42LTggNi42aC0uNmMtMy44IDAtNi42LTIuMy04LTYuNmwtMjQuNC03MC4yLTI0LjYgNzAuMmMtMS4zIDQuMy00LjIgNi42LTcuOSA2LjZoLS40Yy0zLjguMy02LjgtMi04LjMtNi4zbTIxNi40LTg2LjZjMC00IDMuMi03LjQgNy4yLTcuNCA0LjIgMCA3LjQgMy4yIDcuNCA3LjR2MTYuOGM3LjItMTYuMyAyMy4xLTI0IDMzLjctMjQgNC40IDAgNy4yIDMuMiA3LjIgNy40IDAgNC0yLjcgNi44LTYuNSA3LjQtMTguOSAyLjMtMzQuNSAxNi41LTM0LjUgNDQuN3YzMy4yYzAgNC0zIDcuNC03LjIgNy40cy03LjQtMy4yLTcuNC03LjR6bTEwMi4zIDkzLjhjLTI2LjQgMC00Ny45LTIwLjQtNDcuOS01MC40di0uNGMwLTI3LjkgMTkuNS01MC40IDQ2LTUwLjQgMjguNCAwIDQ0LjYgMjMuNCA0NC42IDQ5LjEgMCAzLjktMy4yIDYuOC02LjcgNi44aC02OS40YzIgMjEgMTYuNyAzMi44IDMzLjggMzIuOCAxMS45IDAgMjAuNi00LjcgMjcuNy0xMS4zIDEuMS0uOSAyLjQtMS43IDQuMS0xLjcgMy41IDAgNi4zIDIuOCA2LjMgNi4yIDAgMS43LS43IDMuNC0yLjIgNC43LTkuMiA4LjctMjAgMTQuNi0zNi4zIDE0LjZtMjguNC01Ni4xYy0xLjUtMTcuNi0xMS41LTMzLTMwLjYtMzMtMTYuNyAwLTI5LjMgMTQtMzEuMiAzM3ptLTIzNC4yIDI1Ljh2LS40YzAtMjAuNiAxNy0zMS41IDQxLjctMzEuNSAxMi41IDAgMjEuMyAxLjcgMzAuMSA0LjJ2LTMuNGMwLTE3LjYtMTAuOC0yNi42LTI5LjEtMjYuNi05LjggMC0xNS41IDEuMy0yMi43IDQuNS0uOS40LTEuOS42LTIuNi42LTMuNCAwLTYuNC0yLjgtNi40LTYuMiAwLTMgMS4zLTQuOSA0LTYuMSA5LjYtNC4yIDE2LjktNS42IDI5LjMtNS42IDEzLjggMCAyNC40IDMuNiAzMS41IDEwLjggNi42IDYuNiAxMCAxNi4xIDEwIDI4LjV2NTMuOWMwIDQuMS0zIDcuMi03IDcuMi00LjEgMC02LjktMy02LjktNi44di05LjNjLTYuOCA4LjktMTguMiAxNi44LTM1LjMgMTYuOC0xOC4yLS4yLTM2LjYtMTAuNi0zNi42LTMwLjZtNzItNy42di05LjRjLTcuMi0yLjEtMTYuOC00LjItMjguNy00LjItMTguMyAwLTI4LjUgNy45LTI4LjUgMjAuMnYuNGMwIDEyLjMgMTEuMyAxOS41IDI0LjYgMTkuNSAxNy45IDAgMzIuNi0xMSAzMi42LTI2LjVtLTQ0OS41LTU2LjdjLTMuMi03LTExLjEtMTAuMi0xOC41LTYuOXMtMTAuMSAxMS41LTYuOCAxOC41bDMxIDY3LjRjNC45IDEwLjYgMTAgMTYuMSAxOS43IDE2LjEgMTAuMyAwIDE0LjgtNiAxOS43LTE2LjEgMCAwIDI3LTU4LjkgMjcuMy01OS41czEuMS0yLjUgMy45LTIuNWMyLjMgMCA0LjMgMS45IDQuMyA0LjR2NTcuNmMwIDguOSA0LjkgMTYuMiAxNC40IDE2LjJzMTQuNi03LjMgMTQuNi0xNi4ydi00Ny4xYzAtOS4xIDYuNS0xNSAxNS40LTE1czE0LjggNi4xIDE0LjggMTV2NDcuMWMwIDguOSA0LjkgMTYuMiAxNC40IDE2LjJzMTQuNi03LjMgMTQuNi0xNi4ydi00Ny4xYzAtOS4xIDYuNS0xNSAxNS40LTE1czE0LjggNi4xIDE0LjggMTV2NDcuMWMwIDguOSA0LjkgMTYuMiAxNC40IDE2LjJzMTQuNi03LjMgMTQuNi0xNi4ydi01My42YzAtMTkuNy0xNS44LTMzLjUtMzQuOS0zMy41LTE5IDAtMzEgMTMuMi0zMSAxMy4yLTYuMy04LjMtMTUuMS0xMy4zLTI5LjktMTMuMy0xNS42IDAtMjkuMyAxMy4yLTI5LjMgMTMuMi02LjMtOC4yLTE3LjEtMTMuMi0yNi4xLTEzLjItMTMuOC4xLTI0LjggNi4yLTMxLjUgMjEuNWwtMTkuOCA0Ni43em02MjcuMSA1LjVjMC02LjcgNS4zLTEyLjIgMTIuMS0xMi4yczEyLjEgNS40IDEyLjEgMTJ2LjFjMCA2LjYtNS4zIDEyLjItMTIuMSAxMi4ycy0xMi4xLTUuNS0xMi4xLTEyLjFtMjEuOS0uMWMwLTUuNS00LjItOS45LTkuOC05LjktNS41IDAtOS44IDQuNS05LjggOS45di4xYzAgNS40IDQuMiA5LjkgOS44IDkuOSA1LjUgMCA5LjgtNC42IDkuOC0xMCIvPjxwYXRoIGQ9Im02NjEuMyA4LjljMC0uNy42LTEuMyAxLjMtMS4zaDRjMS41IDAgMi43LjQgMy40IDEuMi43LjYgMSAxLjYgMSAyLjcgMCAxLjgtLjkgMy0yLjMgMy42bDEuOCAyLjJjLjIuMy40LjYuNCAxIDAgLjctLjYgMS4yLTEuMiAxLjJzLTEtLjMtMS4zLS43bC0yLjUtMy4yaC0yLjF2Mi41YzAgLjctLjYgMS4zLTEuMyAxLjNzLTEuMy0uNi0xLjMtMS4zem01LjIgNC40YzEuMyAwIDEuOS0uNyAxLjktMS43IDAtMS4xLS43LTEuNy0yLTEuN2gtMi42djMuNHoiLz48L2c+PC9zdmc+
  keywords:
    - VMware
  maintainers:
    - name: Delphine Joyneer
      email: golkonda.joyneer@wipro.com
    - name: Neelanjan Manna
      email: neelanjan.manna@harness.io
  minKubeVersion: 1.12.0
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Source Code
      url: https://github.com/kubernetes/kubernetes
    - name: Kubernetes Slack
      url: https://slack.kubernetes.io/
    - name: Documentation
      url: "https://litmuschaos.github.io/litmus/experiments/categories/contents/#vmware"
  icon:
    - url: https://github.com/litmuschaos/chaos-charts/blob/master/faults/vmware/icons/vmware.png
      mediatype: image/png
